Take into account vhost users
Use the home directory of the vhost user to store the sftp-only user files.

diff --git a/sftponly/bin/sftponly-useradd b/sftponly/bin/sftponly-useradd
--- a/sftponly/bin/sftponly-useradd
+++ b/sftponly/bin/sftponly-useradd
@@ -1,13 +1,26 @@
 #!/bin/bash
-sftpBaseDir="/var/www/sftp/"
+basedir="/home"
 
-if [ -z "$1" ]
-  then
-    echo "Missing username"
+if [ -z "$1" ]; then
+    echo "Missing vhost username"
+    exit 1
+fi
+vhostUsername="$1"
+
+userExists=$(id -u $vhostUsername > /dev/null 2>&1; echo $?) 
+if [ "$userExists" -ne "0" ]; then
+	echo "vhost user $vhostUsername not found."
+	exit 2
+fi
+
+if [ -z "$2" ]; then
+    echo "Missing sftp username"
     exit 1
 fi
 
-username="sftp-$(date +'%Y%m%d%H%M%S')-$1"
+username="sftp-$(date +'%Y%m%d%H%M%S')-$2"
+homedir="$basedir/sftponly/$vhostUsername/$username"
+userdir="$basedir/$vhostUsername/sftponly/$username"
 
 userExists=$(id -u $username > /dev/null 2>&1; echo $?) 
 if [ "$userExists" -eq "0" ]; then
@@ -15,31 +28,61 @@ if [ "$userExists" -eq "0" ]; then
 	exit 2
 fi
 
-userExists=$(find $sftpBaseDir -name "*$1" 2>/dev/null | wc -l) 
+userExists=$(find $basedir/$vhostUsername/sftponly/ -type d -name "*$2" 2>/dev/null | wc -l) 
 if [ "$userExists" -ne "0" ]; then
-	echo "User $1 already exists."
-	echo $(find $sftpBaseDir -name "*$1")
+	echo "User $2 already exists."
+	echo $(find $basedir/$vhostUsername/sftponly/ -type d -name "*$2")
 	exit 3
 fi
 
-
 echo "Adding SFTP user: $username"
 echo "----------------"
+sftponlyGroup="sftponly"
+vhostSftponlyGroup="$sftponlyGroup-$vhostUsername"
 
-#create the user, becasue all users have /files as their directory it'll say directory already exists
-useradd -g sftpusers -d /files -s /sbin/nologin $username
+#make sure we have a sftpusers group
+$(groupadd $sftponlyGroup 2> /dev/null)
+if [ "$?" -eq "0" ]; then echo "--Added SFTP-Only Group: $sftponlyGroup"; fi
+#and a vhost sftpusers group
+$(groupadd $vhostSftponlyGroup 2> /dev/null)
+if [ "$?" -eq "0" ]; then echo "--Added SFTP-Only $vhostUsername Group: $vhostSftponlyGroup"; fi
+#add vhost user to the their sftp group
+$(usermod -a -G $vhostSftponlyGroup $vhostUsername)
+
+#TODOcreate log file
+
+mkdir -p $homedir/files
+mkdir -p $userdir/files
+
+#store sftp files in vhost users sftp directory
+#static mounting
+#TODO quota
+#mount --bind $userdir/files $homedir/files
+#if [ "$?" -eq "0" ]; then echo "--Mounted: $userdir/files to $homedir/files"; fi
+##mount on reboot
+#tail -1 /etc/mtab >> /etc/fstab
+
+#create the sftp user
+useradd -g $vhostSftponlyGroup -G $sftponlyGroup -d $homedir -s /sbin/nologin $username
+if [ "$?" -eq "0" ]; then echo "--Added user."; fi
 
 #set the password automatically
 #passwd $username, returns 0 on success
 #https://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/
 #userpass=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;)
 userpass=$(openssl rand -base64 18)
-echo -e "$userpass\n$userpass" | passwd $username
+$(echo -e "$userpass\n$userpass" | passwd $username > /dev/null 2>&1)
+if [ "$?" -eq "0" ]; then echo "--Changed password."; fi
 
-#create user sftp files directory (their home directory)
-userdir="$sftpBaseDir$username/files/"
-mkdir -p $userdir
-chown $username $userdir
+chown $username:$vhostSftponlyGroup $homedir/files
+chown $vhostUsername:$vhostUsername $basedir/$vhostUsername/sftponly
+chown $vhostUsername:$vhostUsername $basedir/$vhostUsername/sftponly/$username
+chown $vhostUsername:$vhostSftponlyGroup $basedir/$vhostUsername/sftponly/$username/files
+chmod 775 $basedir/$vhostUsername/sftponly/$username/files
+#setup log file
+touch $userdir/sftp.log
+chown $vhostUsername:$vhostUsername $userdir/sftp.log
+chmod 660 $userdir/sftp.log
 
 echo "---------------"
 echo "Added SFTP user"
diff --git a/sftponly/bin/sftponly-userdel b/sftponly/bin/sftponly-userdel
--- a/sftponly/bin/sftponly-userdel
+++ b/sftponly/bin/sftponly-userdel
@@ -1,23 +1,30 @@
 #!/bin/bash
+basedir="/home"
 
-if [ -z "$1" ]
-  then
-    echo "Missing username"
+if [ -z "$1" ]; then
+    echo "Missing vhost username"
     exit 1
 fi
+vhostUsername="$1"
 
-username="$1"
-
-#validations checks
-userExists=$(id -u $username > /dev/null 2>&1; echo $?) 
-if [ "$userExists" -eq "1" ]; then
-	echo "User $username not found."
+userExists=$(id -u $vhostUsername > /dev/null 2>&1; echo $?) 
+if [ "$userExists" -ne "0" ]; then
+	echo "vhost user $vhostUsername not found."
 	exit 2
 fi
 
-sftpGroup=$(id -nG "$username" | grep -qw "sftpusers" > /dev/null 2>&1; echo $?)
+if [ -z "$2" ]; then
+    echo "Missing sftp username"
+    exit 1
+fi
+
+username="$2"
+homedir="$basedir/sftponly/$vhostUsername/$username"
+userdir="$basedir/$vhostUsername/sftponly/$username"
+
+sftpGroup=$(id -nG "$username" | grep -qw "sftponly" > /dev/null 2>&1; echo $?)
 if [ "$sftpGroup" -eq "1" ]; then
-	echo "User $username not in sftpuser group."
+	echo "User $username not in sftponly group."
 	exit 3
 fi
 
@@ -30,15 +37,26 @@ fi
 echo "Deleting SFTP user: $username"
 echo "------------------"
 
+#in case not unmounted, do it now
+umount $homedir
+if [ "$?" -eq "0" ]; then echo "--Unmounted: $homedir"; fi
+rm -Rf $homedir
+
 #delete user
 userdel -f $username
+if [ "$?" -eq "0" ]; then echo "--Removed user: $username"; fi
 
-#remove sfpt files directory
-userdir="/var/www/sftp/$username"
+#remove sftp files directory
 #rm -Rf $userdir
+echo
+find $userdir
+read -p "Delete users files found above? (yN)" yn
+    case $yn in
+        [Yy]* ) 
+		echo "Deleting files now."; 
+		rm -Rf $userdir;
+		if [ "$?" -eq "0" ]; then echo "--Deleted user files."; fi
+    esac
 
-echo "Deleted SFTP user"
 echo "-----------------"
-echo "Username: $username"
-echo "To remove user files run:"
-echo "# rm -Rf $userdir"
+echo "Deleted SFTP user"
